ForestAdmin/forest-rails

- README.md
- app/services/forest_liana/resources_getter.rb
- test/dummy/app/models/owner.rb
- test/dummy/app/models/tree.rb
- test/dummy/db/migrate/20160627172810_create_owner.rb
- test/dummy/db/migrate/20160627172951_create_tree.rb
- test/dummy/db/schema.rb
- test/fixtures/owner.yml
- test/fixtures/tree.yml
- test/services/forest_liana/resources_getter_test.rb
> Collections - Users want to sort on a "belongsTo/hasOne" field

- app/services/forest_liana/line_stat_getter.rb
- app/services/forest_liana/operator_value_parser.rb
- app/services/forest_liana/pie_stat_getter.rb
- app/services/forest_liana/search_query_builder.rb
- app/services/forest_liana/value_stat_getter.rb
- test/dummy/db/migrate/20160628173505_add_timestamps.rb
- test/dummy/db/schema.rb
- test/fixtures/owner.yml
- test/fixtures/tree.yml
- test/services/forest_liana/resources_getter_test.rb
> Filters - Fix the error while filtering with an ambiguous column of the main collection

- app/services/forest_liana/operator_date_interval_parser.rb
Closes https://github.com/ForestAdmin/forest-rails/issues/16
> Filters - Users want to filter with $blank or $present on a date field

- CHANGELOG.md
- lib/forest_liana/engine.rb
Must have to make Rails users test using the new designed frontapp.
> [-] CORS - Enable all forestadmin.com subdomains to requests the liana

- CHANGELOG.md
- app/services/forest_liana/pie_stat_getter.rb
Fixes: https://github.com/ForestAdmin/forest-rails/issues/110
> [*] Pie Charts - Fix the computation of Pie Charts having a groupBy on a belongsTo relationship

- CHANGELOG.md
- app/controllers/forest_liana/resources_controller.rb
- app/services/forest_liana/value_stat_getter.rb
Fixes: https://github.com/ForestAdmin/forest-rails/issues/125
> [*] Fix the behaviour of collections having a foreign keys that is not named "id"

- CHANGELOG.md
- lib/forest_liana/bootstraper.rb
Fixes: https://github.com/ForestAdmin/forest-rails/issues/132
> [*] Server Start - Fix the server crash on start while offline

- CHANGELOG.md
- app/services/forest_liana/search_query_builder.rb
Not sure about the implementation, would love to have your feedback @arnaudbesnier and @lucasscariot
> [+] Acts on taggable - Search & Filters

- CHANGELOG.md
- lib/forest_liana/bootstraper.rb
- lib/forest_liana/collection.rb
> [+] Smart Collections - Add a new isSearchable property to display the search bar for Smart Collections

- CHANGELOG.md
- app/helpers/forest_liana/adapter_helper.rb
- app/services/forest_liana/operator_value_parser.rb
- test/services/forest_liana/value_stat_getter_test.rb
> [*] Charts - Fix charts having filters on associations fields

- CHANGELOG.md
- lib/forest_liana/bootstraper.rb
- test/services/forest_liana/resource_updater_test.rb
> [+] Technical -  Send rails and activerecord version in apimap

- CHANGELOG.md
- app/controllers/forest_liana/application_controller.rb
- app/controllers/forest_liana/router.rb
> [*] Router - Catch resources routing errors with a 404 response instead of a crash

- CHANGELOG.md
- app/services/forest_liana/value_stat_getter.rb
Fix https://github.com/ForestAdmin/forest-rails/issues/165
> [*] Deprecation Warning - Remove a deprecation warning on Chart request due to uniq method

- CHANGELOG.md
- app/services/forest_liana/has_many_getter.rb
- app/services/forest_liana/search_query_builder.rb
- test/dummy/app/models/owner.rb
- test/fixtures/tree.yml
- test/services/forest_liana/has_many_getter_test.rb
> [+] Search - Users can search on the hasMany associated data of a specific record

- CHANGELOG.md
- app/services/forest_liana/pie_stat_getter.rb
- test/services/forest_liana/pie_stat_getter_test.rb
> [*] Pie Charts - Fix potential pie chart rendering issue using Rails 5

- CHANGELOG.md
- app/deserializers/forest_liana/resource_deserializer.rb
> [*] Record Updates - Do not try to update the Smart Fields if no new value is send in the update request

- CHANGELOG.md
- forest_liana.gemspec
> [-] Technical - Update .gemspec file to specify that Rails 3 is not maintained anymore

- CHANGELOG.md
- app/services/forest_liana/schema_adapter.rb
> [+] Fields - Send the defaultValue for creation forms

- CHANGELOG.md
- app/controllers/forest_liana/application_controller.rb
- app/controllers/forest_liana/associations_controller.rb
- app/controllers/forest_liana/resources_controller.rb
- app/controllers/forest_liana/router.rb
- app/services/forest_liana/has_many_getter.rb
- app/services/forest_liana/resources_getter.rb
- lib/forest_liana/collection.rb
> [+] Exports - Forest can now handle large data exports

- CHANGELOG.md
- app/services/forest_liana/search_query_builder.rb
> [-] Search - Split "simple" and "deep" search features with a new param

- CHANGELOG.md
- app/services/forest_liana/schema_adapter.rb
> [*] Validations - Do not consider conditional validations for Forest forms validation

- CHANGELOG.md
- app/services/forest_liana/schema_adapter.rb
Fix https://github.com/ForestAdmin/forest-rails/issues/180
> [*] Validations - Do not consider validations if an Active Record before_validation Callback is defined in the model

- CHANGELOG.md
- app/controllers/forest_liana/application_controller.rb
> [*] Exports - Fix bad initial implementation for exports authentication

- CHANGELOG.md
- app/controllers/forest_liana/application_controller.rb
> [*] Exports - Fix some issues with the new export feature

- CHANGELOG.md
- app/services/forest_liana/base_getter.rb
- app/services/forest_liana/has_many_getter.rb
- app/services/forest_liana/line_stat_getter.rb
- app/services/forest_liana/pie_stat_getter.rb
- app/services/forest_liana/resource_getter.rb
- app/services/forest_liana/resources_getter.rb
- app/services/forest_liana/stat_getter.rb
- app/services/forest_liana/value_stat_getter.rb
To install the Gem follow the README: https://github.com/rubysherpas/paranoia
Fix inconsistencies described here: https://github.com/ForestAdmin/forest-rails/issues/177
> [+] Paranoid Mode - Support Paranoia gem and hide all "deleted" data in Forest

- CHANGELOG.md
- app/models/forest_liana/model/collection.rb
- app/services/forest_liana/base_getter.rb
- app/services/forest_liana/has_many_getter.rb
- app/services/forest_liana/resources_getter.rb
- app/services/forest_liana/search_query_builder.rb
- lib/forest_liana/collection.rb
> [+] Search - Developers can configure in which fields the search will be executed.

- CHANGELOG.md
- config/routes.rb
- test/routing/route_test.rb
> [*] Stripe - Fix the Stripe Payments access

- CHANGELOG.md
- lib/generators/forest_liana/install_generator.rb
Fixes: https://github.com/ForestAdmin/forest-rails/issues/188
> [*] Onboarding - Fix the automatic secrets.yml setup on projects using Rails 5.1+

- CHANGELOG.md
- app/serializers/forest_liana/serializer_factory.rb
- lib/forest_liana/collection.rb
> Facilitate the way to create Smart Collections

- CHANGELOG.md
- lib/forest_liana/collection.rb
> [+] Smart Collections - Add a field parameter to allow the sorting.

- CHANGELOG.md
- app/services/forest_liana/resources_getter.rb
- app/services/forest_liana/schema_utils.rb
- app/services/forest_liana/search_query_builder.rb
```ruby
class Forest::Bike
include ForestLiana::Collection
collection :bikes
search_fields ['name', 'movie.title', 'customers.email'] # customers is a hasMany relationship
end
```
> [+] Smart Search - Developers can configure a Smart Search on a hasMany relationship

- CHANGELOG.md
- app/services/forest_liana/pie_stat_getter.rb
> [*] Pie Charts - Fix enum values display on Pie Charts for latest Rails version users

- CHANGELOG.md
- app/services/forest_liana/schema_adapter.rb
- lib/forest_liana/bootstraper.rb
- lib/forest_liana/collection.rb
- test/services/forest_liana/schema_adapter_test.rb
> [+] Smart Fields - Add a "is_filterable" option to let them appear in the filters selection

- CHANGELOG.md
- app/services/forest_liana/operator_value_parser.rb
- test/dummy/app/models/has_one_field.rb
- test/dummy/db/migrate/20150608133044_create_has_one_field.rb
- test/dummy/db/schema.rb
- test/fixtures/has_one_field.yml
- test/services/forest_liana/value_stat_getter_test.rb
> [*] Charts - Fix belongsTo filters on enum fields

- CHANGELOG.md
- app/controllers/forest_liana/application_controller.rb
- app/controllers/forest_liana/associations_controller.rb
- app/controllers/forest_liana/resources_controller.rb
> [*] Export CSV - Enable the CSV export for namespaced models

- CHANGELOG.md
- lib/forest_liana/collection.rb
> [-] Smart Fields - Prevent the Smart Fields computation errors to gererate a crash and handle it letting the value empty.

- CHANGELOG.md
- app/controllers/forest_liana/application_controller.rb
- app/controllers/forest_liana/intercom_controller.rb
- app/serializers/forest_liana/intercom_attribute_serializer.rb
- app/serializers/forest_liana/intercom_conversation_serializer.rb
- app/services/forest_liana/intercom_attributes_getter.rb
- app/services/forest_liana/intercom_conversation_getter.rb
- app/services/forest_liana/intercom_conversations_getter.rb
- config/routes.rb
- lib/forest_liana/bootstraper.rb
- test/routing/route_test.rb
> [-] Intercom Integration - Prefer Intercom access_token configuration to old fashioned app_id/api_key

- CHANGELOG.md
- app/services/forest_liana/has_many_getter.rb
> [*] HasMany Getter - Fix HasMany associated records retrieval for namespaced models

- CHANGELOG.md
- app/controllers/forest_liana/associations_controller.rb
- app/controllers/forest_liana/resources_controller.rb
- app/models/forest_liana/model/collection.rb
- app/serializers/forest_liana/collection_serializer.rb
- app/services/forest_liana/has_many_getter.rb
- app/services/forest_liana/resources_getter.rb
- app/services/forest_liana/schema_adapter.rb
- app/services/forest_liana/schema_utils.rb
- lib/forest_liana.rb
- lib/forest_liana/bootstraper.rb
- lib/forest_liana/version.rb
- test/services/forest_liana/has_many_getter_test.rb
- test/services/forest_liana/resource_updater_test.rb
- test/services/forest_liana/resources_getter_test.rb
- test/services/forest_liana/schema_adapter_test.rb
Fix: https://github.com/ForestAdmin/forest-rails/issues/123
> [+] STI Models - Support STI Models with a collection for the parent model and each child model, with automatic segments on the parent collection

- CHANGELOG.md
- app/controllers/forest_liana/router.rb
- app/serializers/forest_liana/serializer_factory.rb
- app/services/forest_liana/controller_factory.rb
- lib/forest_liana.rb
- lib/forest_liana/bootstraper.rb
- lib/forest_liana/collection.rb
Fix: https://github.com/ForestAdmin/forest-rails/issues/210
> [*] Server Start - Prevent potential error on server start [regression introduced by the version 2]

- CHANGELOG.md
- lib/forest_liana/bootstraper.rb
> [*] Serializer - Fix 'already defined' warning message on server start.

- CHANGELOG.md
- lib/forest_liana/bootstraper.rb
> [*] Start - Prevent a crash if the server is restarting while Forest services are in maintenance

- CHANGELOG.md
- lib/forest_liana/bootstraper.rb
Fix: https://github.com/ForestAdmin/forest-rails/issues/215
> [*] Initialisation - Fix a potential error on database type retrieval on server start

- CHANGELOG.md
- app/controllers/forest_liana/application_controller.rb
- app/controllers/forest_liana/associations_controller.rb
- app/controllers/forest_liana/resources_controller.rb
> [-] Smart Fields - Compute only the necessary Smart Fields values for list views and CSV exports

- CHANGELOG.md
- app/services/forest_liana/query_stat_getter.rb
> [*] Live Queries - Prevent the execution of obvious "write" queries

- CHANGELOG.md
- app/services/forest_liana/operator_date_interval_parser.rb
- test/services/forest_liana/resources_getter_test.rb
> [+] Filters - Add a new "is after X hours ago" operator to filter on date fields

- CHANGELOG.md
- app/deserializers/forest_liana/resource_deserializer.rb
- app/serializers/forest_liana/serializer_factory.rb
- app/services/forest_liana/schema_adapter.rb
> [*] Devise - Users now have a password field and can create records for models using Devise gem

- CHANGELOG.md
- app/controllers/forest_liana/application_controller.rb
- app/controllers/forest_liana/associations_controller.rb
- app/controllers/forest_liana/resources_controller.rb
> [*] Search - Prevent the records search to crash if no fields parameter is sent by the client

- CHANGELOG.md
- lib/forest_liana/bootstraper.rb
> [*] Smart Actions - Display the Smart Actions form fields in the declaration order

- CHANGELOG.md
- app/models/forest_liana/model/action.rb
- app/serializers/forest_liana/action_serializer.rb
- lib/forest_liana/bootstraper.rb
> [+] Smart Actions - Users can define Smart Actions only available in a record detail

- CHANGELOG.md
- app/services/forest_liana/has_many_dissociator.rb
> [+] Related Data - Delete records directly from a hasMany listing

- CHANGELOG.md
- app/controllers/forest_liana/actions_controller.rb
- app/controllers/forest_liana/application_controller.rb
- config/routes.rb
> [+] Smart Actions - "Single" type Smart Action forms can now be prefilled with contextual values

- CHANGELOG.md
- app/controllers/forest_liana/associations_controller.rb
- app/controllers/forest_liana/resources_controller.rb
- app/models/forest_liana/model/collection.rb
- app/services/forest_liana/base_getter.rb
- app/services/forest_liana/resource_getter.rb
> [*] Smart Relationships - Fix the serialization of Smart belongs_to relationships in lists and record details

- CHANGELOG.md
- app/controllers/forest_liana/resources_controller.rb
- app/controllers/forest_liana/stats_controller.rb
- app/services/forest_liana/live_query_checker.rb
- app/services/forest_liana/query_stat_getter.rb
- app/services/forest_liana/resources_getter.rb
- config/initializers/errors.rb
> [+] Segments - Users can create segments with SQL queries

- CHANGELOG.md
- app/controllers/forest_liana/resources_controller.rb
- app/services/forest_liana/forest_api_requester.rb
- app/services/forest_liana/forest_server_requester.rb
- app/services/forest_liana/permissions_checker.rb
- app/services/forest_liana/permissions_getter.rb
- app/services/forest_liana/users_getter.rb
> [+] Permissions - Add a permission mechanism to protect the data accordingly to the UI configuration

- CHANGELOG.md
- app/services/forest_liana/has_many_getter.rb
> [-] Performance - Make the related data count retrieval much more efficient if the result contains thousands of records

- CHANGELOG.md
- lib/generators/forest_liana/install_generator.rb
> [*] Onboarding - The install generator now supports credentials.yml.enc file introduced in Rails 5.2

- CHANGELOG.md
- app/controllers/forest_liana/application_controller.rb
- app/controllers/forest_liana/stripe_controller.rb
- app/services/forest_liana/stripe_invoice_getter.rb
- app/services/forest_liana/stripe_invoices_getter.rb
- app/services/forest_liana/stripe_payment_getter.rb
- app/services/forest_liana/stripe_payment_refunder.rb
- app/services/forest_liana/stripe_payments_getter.rb
- app/services/forest_liana/stripe_source_getter.rb
- app/services/forest_liana/stripe_sources_getter.rb
- app/services/forest_liana/stripe_subscription_getter.rb
- app/services/forest_liana/stripe_subscriptions_getter.rb
> [*] Stripe Integration - Improve the error handling if the customer Stripe Id is not found

- CHANGELOG.md
- app/controllers/forest_liana/application_controller.rb
- app/controllers/forest_liana/associations_controller.rb
- app/controllers/forest_liana/resources_controller.rb
- app/controllers/forest_liana/router.rb
- app/services/forest_liana/has_many_getter.rb
- app/services/forest_liana/resources_getter.rb
- config/routes.rb
- test/routing/route_test.rb
> [-] Performance - Improve the speed of listing the records by executing their count into another request

- CHANGELOG.md
- app/controllers/forest_liana/application_controller.rb
- app/controllers/forest_liana/base_controller.rb
- app/services/forest_liana/search_query_builder.rb
> [*] Collections - Fixes potential behaviour issues of collections having a name that collides with query params keys

- CHANGELOG.md
- app/services/forest_liana/schema_adapter.rb
>  [*] STI Models - Make the field corresponding to the inheritance_column accessible to STI parent models that dont have children

- CHANGELOG.md
- app/controllers/forest_liana/resources_controller.rb
- app/services/forest_liana/has_many_dissociator.rb
> [-] Records Deletion - Delete a record which has already been deleted does not display an error anymore

- CHANGELOG.md
- app/services/forest_liana/resources_getter.rb
- Create a table `articles` with a column `name`, and a table`comments` with a column `content` and `article`
- Create a live query segment on `comments`: `SELECT o.id FROM articles o;`
- Go to you segment
To polulate your db:
```
insert into articles (
name
)
select
md5(random()::text)
from generate_series(1, 1000000) s(i);
insert into comments (
content, article_id
)
select
md5(random()::text),
floor(random() * (3-1 + 1) + 1)
from generate_series(1, 1000000) s(i);
```
Before:
After:
> [*] Live Query Segment - Optimize resource retrieving to avoid using too much memory

- CHANGELOG.md
- app/controllers/forest_liana/resources_controller.rb
- app/services/forest_liana/operator_value_parser.rb
- test/services/forest_liana/resources_getter_test.rb
> [*] Segment - Handle association error on resource count 

- CHANGELOG.md
- Gemfile.lock
More information: https://devcenter.heroku.com/changelog-items/1437
> [*] Security - Upgrade sprockets dependency version to fix a known vulnerability

- CHANGELOG.md
- app/services/forest_liana/resources_getter.rb
- test/dummy/app/models/reference.rb
- test/dummy/db/migrate/20181111162121_create_references_table.rb
- test/dummy/db/schema.rb
- test/fixtures/reference.yml
- test/services/forest_liana/resources_getter_test.rb
> [*] Models - Fix models having a table name being a reserved SQL word

- CHANGELOG.md
- lib/forest_liana/bootstraper.rb
> [+] Technical - On start, create a forestadmin.json file that contains the apimap definition

- CHANGELOG.md
- app/controllers/forest_liana/stats_controller.rb
- app/serializers/forest_liana/stat_serializer.rb
- app/services/forest_liana/leaderboard_stat_getter.rb
- app/services/forest_liana/line_stat_getter.rb
- app/services/forest_liana/objective_stat_getter.rb
- app/services/forest_liana/query_stat_getter.rb
- app/services/forest_liana/schema_adapter.rb
- lib/forest_liana/bootstraper.rb
- test/services/forest_liana/schema_adapter_test.rb
> [+] Charts - Users can create Objective and Leaderboard Charts

- CHANGELOG.md
- app/services/forest_liana/base_getter.rb
- app/services/forest_liana/has_many_getter.rb
- app/services/forest_liana/leaderboard_stat_getter.rb
- app/services/forest_liana/line_stat_getter.rb
- app/services/forest_liana/pie_stat_getter.rb
- app/services/forest_liana/resource_getter.rb
- app/services/forest_liana/resources_getter.rb
- app/services/forest_liana/search_query_builder.rb
- app/services/forest_liana/stat_getter.rb
- app/services/forest_liana/value_stat_getter.rb
> [*] Filters - Fix association filtering on collections having several associations targeting the same table

- CHANGELOG.md
- app/controllers/forest_liana/application_controller.rb
> [-] Security - Do not pass session token in query params while downloading collections records

- CHANGELOG.md
- app/services/forest_liana/search_query_builder.rb
> [*] Search - Enable PostgreSQL's CITEXT fields in search.

- app/deserializers/forest_liana/resource_deserializer.rb
> [*] Devise Support - Avoid setting devise password to nil on record update

- CHANGELOG.md
- app/controllers/forest_liana/application_controller.rb
- app/services/forest_liana/login_handler.rb
- spec/requests/resources_spec.rb
> [-] Technical - Makes the JWT lighter and consistent across lianas

- CHANGELOG.md
- app/services/forest_liana/search_query_builder.rb
> [*] Filters - Fix issue where 'or' filter is not handled on belongsTo/hasOne associations.

- CHANGELOG.md
- lib/forest_liana/bootstrapper.rb
- lib/forest_liana/engine.rb
- lib/tasks/display_apimap.rake
- lib/tasks/send_apimap.rake
> Fix typo bootstraper -> bootstrapper

- CHANGELOG.md
- app/services/forest_liana/resource_creator.rb
- app/services/forest_liana/resource_updater.rb
- lib/forest_liana/bootstrapper.rb
- lib/forest_liana/engine.rb
> [+] Rails Versions - Support Rails 6 projects

- CHANGELOG.md
- Gemfile.lock
- app/controllers/forest_liana/resources_controller.rb
- app/controllers/forest_liana/router.rb
- app/services/forest_liana/has_many_dissociator.rb
- app/services/forest_liana/resources_getter.rb
- config/routes.rb
- lib/forest_liana/version.rb
- package.json
v5
See: https://github.com/ForestAdmin/forest-rails/pull/345
> [+] Resources getter - Add a get_ids_from_request method to get all models IDs given a query or an ID list (#345)

- CHANGELOG.md
- package.json
> [*] Technical - Fix the license type in the `package.json` file

- CHANGELOG.md
- app/controllers/forest_liana/application_controller.rb
- app/controllers/forest_liana/smart_actions_controller.rb
- app/services/forest_liana/permissions_checker.rb
[ClickUp](https://app.clickup.com/t/4jq863)
> feat(smart-action): allow users to protect their smart-action APIs from unauthorized usage (#4jq863)

- app/controllers/forest_liana/resources_controller.rb
- app/services/forest_liana/permissions_checker.rb
- app/services/forest_liana/scope_validator.rb
- test/services/forest_liana/scope_validator_test.rb
> feat(scope): validate scope context on list/count request

- package.json
- yarn.lock
Clickup card: https://app.clickup.com/t/6up7hd
> fix(vulnerability): patch a potential vulnerability updating lodash dependency

- README.md
> docs(readme): fix an url in the Readme

- lib/forest_liana/bootstrapper.rb
To test it efficiently, you will need the updated [server](https://github.com/ForestAdmin/forestadmin-server/pull/1820)
> refactor(schema): remove unused `framework_version` attribute from the schema

- app/services/forest_liana/filters_parser.rb
Fix: https://github.com/ForestAdmin/forest-rails/issues/378
> fix(filter): fix filtering with projects on Rails 5.1

- app/controllers/forest_liana/authentication_controller.rb
- app/controllers/forest_liana/stats_controller.rb
- app/helpers/forest_liana/adapter_helper.rb
- app/serializers/forest_liana/schema_serializer.rb
- app/services/forest_liana/apimap_sorter.rb
- app/services/forest_liana/authentication.rb
- app/services/forest_liana/ip_whitelist_checker.rb
- app/services/forest_liana/oidc_client_manager.rb
- app/services/forest_liana/oidc_configuration_retriever.rb
- app/services/forest_liana/oidc_dynamic_client_registrator.rb
- app/services/forest_liana/permissions_checker.rb
- app/services/forest_liana/query_stat_getter.rb
- lib/forest_liana/bootstrapper.rb
- lib/forest_liana/collection.rb
- lib/forest_liana/json_printer.rb
- spec/requests/authentications_spec.rb
- spec/services/forest_liana/schema_adapter_spec.rb
> fix(syntax): remove useless semicolons

- .travis.yml
> ci(beta): enable beta releases

- app/controllers/forest_liana/actions_controller.rb
- app/controllers/forest_liana/application_controller.rb
- app/helpers/forest_liana/is_same_data_structure_helper.rb
- app/models/forest_liana/model/action.rb
- app/services/forest_liana/apimap_sorter.rb
- app/services/forest_liana/resources_getter.rb
- config/routes.rb
- lib/forest_liana/bootstrapper.rb
- lib/forest_liana/schema_file_updater.rb
- spec/helpers/forest_liana/is_same_data_structure_helper_spec.rb
- spec/requests/actions_controller_spec.rb
- spec/services/forest_liana/apimap_sorter_spec.rb
- spec/services/forest_liana/schema_adapter_spec.rb
> feat: handle hooks

- app/controllers/forest_liana/actions_controller.rb
- spec/requests/actions_controller_spec.rb
> fix(smart-actions): use changedField instead of comparing values to trigger the correct change hook

- app/controllers/forest_liana/actions_controller.rb
- spec/requests/actions_controller_spec.rb
> fix(smart-actions): reset value when not present in enums in hook response

- spec/requests/actions_controller_spec.rb
> fix(hooks): fix test after enums support

- app/services/forest_liana/permissions_checker.rb
- app/services/forest_liana/permissions_formatter.rb
- app/services/forest_liana/permissions_getter.rb
- app/services/forest_liana/scope_validator.rb
- spec/services/forest_liana/permissions_checker_acl_disabled_spec.rb
- spec/services/forest_liana/permissions_checker_acl_enabled_spec.rb
- spec/services/forest_liana/permissions_formatter_spec.rb
- spec/services/forest_liana/permissions_getter_spec.rb
> feat(role): add support for scopes among new roles ACL permissions

- app/controllers/forest_liana/resources_controller.rb
- app/controllers/forest_liana/smart_actions_controller.rb
- app/services/forest_liana/permissions_checker.rb
- app/services/forest_liana/permissions_formatter.rb
- app/services/forest_liana/permissions_getter.rb
- app/services/forest_liana/scope_validator.rb
- app/services/forest_liana/utils/beta_schema_utils.rb
- spec/services/forest_liana/permissions_checker_acl_disabled_spec.rb
- spec/services/forest_liana/permissions_checker_acl_enabled_spec.rb
- spec/services/forest_liana/permissions_formatter_spec.rb
- spec/services/forest_liana/permissions_getter_spec.rb
> feat(role): add support for new roles ACL permissions

- Gemfile.lock
- app/controllers/forest_liana/authentication_controller.rb
- app/services/forest_liana/oidc_client_manager.rb
- lib/forest_liana.rb
- spec/requests/authentications_spec.rb
- test/services/forest_liana/resources_getter_test.rb
> fix(auth): support multi instances agents and send back response to frontend instead of redirecting

- test/services/forest_liana/resources_getter_test.rb
> test: fix Time.now date comparison in test

- app/controllers/forest_liana/actions_controller.rb
- spec/requests/actions_controller_spec.rb
> fix(smart-action-hook): value injected to an enum field of type is now correctly handled

- README.md
> docs(readme): update 'How it Works' visual

- README.md
- commitlint.config.js
- package.json
- yarn.lock
> docs(readme): fix the CI status badge

- app/services/forest_liana/schema_utils.rb
> fix: display a warning on missing association

- commitlint.config.js
> ci: allow longer commit messages

- app/controllers/forest_liana/authentication_controller.rb
- app/services/forest_liana/oidc_client_manager.rb
- lib/forest_liana/bootstrapper.rb
- lib/generators/forest_liana/install_generator.rb
> fix(authentication): add missing environment variable generation and check if caching is enabled (#epz6k0)

- app/controllers/forest_liana/authentication_controller.rb
- spec/requests/authentications_spec.rb
> fix(authentication): properly setup the session cookie to restore authentication on remote environments

- app/controllers/forest_liana/authentication_controller.rb
- spec/requests/authentications_spec.rb
> fix(authentication): safari cannot login on remote lianas because of third party cookies

- app/services/forest_liana/token.rb
This PR introduces changes that will be used by the future refresh token system.
> fix(serurity): decrease token expiration time to 1 hour

- app/controllers/forest_liana/stats_controller.rb
- app/services/forest_liana/permissions_checker.rb
- spec/requests/stats_spec.rb
- spec/services/forest_liana/permissions_checker_acl_disabled_spec.rb
- spec/services/forest_liana/permissions_checker_acl_enabled_spec.rb
- spec/services/forest_liana/permissions_checker_live_queries_spec.rb
> feat(security): authorised only allowed stats queries using permissions

- app/services/forest_liana/permissions_checker.rb
> fix(security): forest stats api 403 forbidden at chart creation

- app/models/forest_liana/model/action.rb
- app/services/forest_liana/apimap_sorter.rb
- lib/forest_liana/schema_file_updater.rb
- spec/requests/actions_controller_spec.rb
> feat(smart-action):​ handle isReadOnly field in smart action forms

- app/services/forest_liana/oidc_client_manager.rb
> fix(authentication): fix authentication errors after deploying a new instance with the same code (#gb01xz)

- .github/workflows/build.yml
> ci: upgrade bundler to version 2.1.4

- app/controllers/forest_liana/authentication_controller.rb
- lib/forest_liana/bootstrapper.rb
> fix: allow actions hooks in production

- app/controllers/forest_liana/stats_controller.rb
- app/services/forest_liana/permissions_checker.rb
- spec/requests/stats_spec.rb
> fix: distribution charts using groupby on a relationship should not throws 403 Forbidden

- app/services/forest_liana/line_stat_getter.rb
- spec/services/forest_liana/line_stat_getter_spec.rb
> fix: fix timebased charts display with groupdate 5.2 and ruby 3.0

- .github/workflows/build.yml
Should be similar to any other contribution related to the addition of the beta distribution channel, eg [here](https://github.com/ForestAdmin/forest-express/blob/master/.github/workflows/build.yml)
> chore(beta): add beta distribution channel

- .releaserc.js
> chore: allow to force a release with force-release scope

- .releaserc.js
> chore: merge master into beta

- app/services/forest_liana/line_stat_getter.rb
> fix: fix time based graph when timezone is different with database

- Gemfile.lock
> chore: fix 7.0.0-beta.1 version mismatch in Gemfile.lock

- README.md
> docs(readme): fix alt text in README

- app/services/forest_liana/token.rb
- spec/requests/authentications_spec.rb
> feat: include role in the user data inside the request

- app/services/forest_liana/permissions_checker.rb
> fix: support permissions infos with ruby < 2.7

- app/services/forest_liana/scope_manager.rb
- spec/services/forest_liana/scope_manager_spec.rb
> feat: add scope manager

- app/controllers/forest_liana/scopes_controller.rb
- app/services/forest_liana/scope_manager.rb
- config/routes.rb
- spec/services/forest_liana/scope_manager_spec.rb
> feat: add scope cache invalidation route

- app/services/forest_liana/permissions_checker.rb
- spec/services/forest_liana/permissions_checker_acl_enabled_spec.rb
- spec/services/forest_liana/permissions_checker_live_queries_spec.rb
> fix: stats permissions should be retrieved only one time per team

- Gemfile
- Gemfile.lock
- app/controllers/forest_liana/associations_controller.rb
- app/controllers/forest_liana/resources_controller.rb
- app/services/forest_liana/has_many_getter.rb
- app/services/forest_liana/permissions_checker.rb
- app/services/forest_liana/resources_getter.rb
- app/services/forest_liana/scope_manager.rb
- app/services/forest_liana/search_query_builder.rb
- spec/requests/resources_spec.rb
- spec/services/forest_liana/resources_getter_spec.rb
- spec/services/forest_liana/scope_manager_spec.rb
- test/services/forest_liana/has_many_getter_test.rb
- test/test_helper.rb
> feat: add scope filters to ResourcesGetter and HasManyGetter

- app/controllers/forest_liana/stats_controller.rb
- app/services/forest_liana/leaderboard_stat_getter.rb
- app/services/forest_liana/line_stat_getter.rb
- app/services/forest_liana/pie_stat_getter.rb
- app/services/forest_liana/stat_getter.rb
- app/services/forest_liana/value_stat_getter.rb
- spec/requests/actions_controller_spec.rb
- spec/services/forest_liana/line_stat_getter_spec.rb
- test/services/forest_liana/pie_stat_getter_test.rb
- test/services/forest_liana/value_stat_getter_test.rb
> feat: add scopes to all charts

- Gemfile.lock
- app/controllers/forest_liana/resources_controller.rb
- app/services/forest_liana/permissions_checker.rb
- app/services/forest_liana/permissions_formatter.rb
- app/services/forest_liana/permissions_getter.rb
- spec/services/forest_liana/permissions_checker_acl_disabled_spec.rb
- spec/services/forest_liana/permissions_checker_acl_enabled_spec.rb
- spec/services/forest_liana/permissions_checker_live_queries_spec.rb
- spec/services/forest_liana/permissions_formatter_spec.rb
> feat(security): secure segments queries

- app/controllers/forest_liana/actions_controller.rb
- spec/requests/actions_controller_spec.rb
> chore: edit smart action hook routes to use JSONAPI request format

- app/controllers/forest_liana/actions_controller.rb
- app/controllers/forest_liana/application_controller.rb
- config/routes.rb
- spec/dummy/tmp/cache/11D/A92/http%3A%2F%2Flocalhost%3A3000%2Fforest%2Fauthentication%2Fcallback-env_secret_test-client-data
- spec/requests/actions_controller_spec.rb
BREAKING CHANGE: record is no longer send to the hook midleware
values option on smart action is no longer supported
> feat: smart action hooks now have access to the http request

- app/controllers/forest_liana/actions_controller.rb
- app/models/forest_liana/model/action.rb
- spec/dummy/tmp/cache/11D/A92/http%3A%2F%2Flocalhost%3A3000%2Fforest%2Fauthentication%2Fcallback-env_secret_test-client-data
- spec/requests/actions_controller_spec.rb
> fix(hooks): smart action hooks response correctly send back serialized fields

- app/services/forest_liana/filters_parser.rb
- spec/services/forest_liana/filters_parser_spec.rb
> feat(filter): add "is in" filter

- app/services/forest_liana/permissions_checker.rb
- spec/services/forest_liana/permissions_checker_acl_disabled_spec.rb
- spec/services/forest_liana/permissions_checker_acl_enabled_spec.rb
> fix: smart actions restricted to a segment using segment query should be visible

- .releaserc.js
> chore: allow to release patches on previous versions

- .github/workflows/build.yml
> chore: build the branch 6.x.x

- config/initializers/httpclient.rb
> fix(authentication): fix certificate issues that break the authentication

- app/controllers/forest_liana/actions_controller.rb
- app/controllers/forest_liana/associations_controller.rb
- app/controllers/forest_liana/base_controller.rb
- app/controllers/forest_liana/resources_controller.rb
- app/controllers/forest_liana/router.rb
- app/controllers/forest_liana/scopes_controller.rb
- app/controllers/forest_liana/smart_actions_controller.rb
- app/controllers/forest_liana/stats_controller.rb
- app/services/forest_liana/intercom_attributes_getter.rb
- app/services/forest_liana/intercom_conversation_getter.rb
- app/services/forest_liana/intercom_conversations_getter.rb
- app/services/forest_liana/ip_whitelist.rb
- app/services/forest_liana/permissions_getter.rb
- app/services/forest_liana/resources_getter.rb
- app/services/forest_liana/schema_adapter.rb
- app/services/forest_liana/search_query_builder.rb
- app/services/forest_liana/stripe_invoices_getter.rb
- app/services/forest_liana/stripe_payments_getter.rb
- app/services/forest_liana/stripe_sources_getter.rb
- app/services/forest_liana/stripe_subscriptions_getter.rb
- config/initializers/logger.rb
- lib/forest_liana.rb
- lib/forest_liana/bootstrapper.rb
- lib/forest_liana/collection.rb
- lib/forest_liana/engine.rb
- lib/forest_liana/schema_file_updater.rb
- spec/config/initializers/logger_spec.rb
Linked PR https://github.com/ForestAdmin/forest-rails/pull/325
Clickup card https://app.clickup.com/t/9r265k
> feat(reporter): customers can now catch every errors thrown by forest

- lib/forest_liana/bootstrapper.rb
> fix: avoid attaching smart action hooks on pre-defined smart actions

- app/controllers/forest_liana/actions_controller.rb
- spec/dummy/tmp/cache/11D/A92/http%3A%2F%2Flocalhost%3A3000%2Fforest%2Fauthentication%2Fcallback-env_secret_test-client-data
- spec/requests/actions_controller_spec.rb
> fix: add user inside context for smart actions hooks

- spec/dummy/tmp/cache/11D/A92/http%3A%2F%2Flocalhost%3A3000%2Fforest%2Fauthentication%2Fcallback-env_secret_test-client-data
> chore: remove spec tmp file

- Gemfile
- Gemfile.lock
This reverts commit 176afff36718964768401e03d89de583db810514.
> fix : revert "fix: update arel-helpers dependency (#535)"

- Gemfile
- Gemfile.lock
> fix: onboarding with rails 7 when running "rails g forest_liana:install"

- app/controllers/forest_liana/application_controller.rb
- app/controllers/forest_liana/resources_controller.rb
- spec/dummy/config/routes.rb
- spec/dummy/lib/forest_liana/controllers/owners_controller.rb
- spec/requests/count_spec.rb
> feat(count): add deactivate count support

- app/controllers/forest_liana/application_controller.rb
- app/controllers/forest_liana/associations_controller.rb
- app/controllers/forest_liana/resources_controller.rb
- spec/dummy/app/models/owner.rb
- spec/dummy/config/routes.rb
- spec/dummy/lib/forest_liana/controllers/owner_trees_controller.rb
- spec/requests/count_spec.rb
> fix: add support count deactivate on relationships resources

- lib/forest_liana/bootstrapper.rb
- spec/lib/forest_liana/bootstrapper_spec.rb
> fix(apimap): fix generate schema with unknown action

- app/services/forest_liana/search_query_builder.rb
> fix(search): fix search on fields of type UUID

- app/services/forest_liana/schema_adapter.rb
- spec/services/forest_liana/schema_adapter_spec.rb
> fix: sort fields in schema

- app/services/forest_liana/base_getter.rb
- spec/dummy/app/models/car.rb
- spec/dummy/app/models/driver.rb
- spec/dummy/app/models/garage_record.rb
- spec/dummy/app/models/user_record.rb
- spec/dummy/config/database.yml
- spec/dummy/db/migrate/20220719094127_create_cars.rb
- spec/dummy/db/migrate/20220719094450_create_drivers.rb
- spec/lib/forest_liana/bootstrapper_spec.rb
> fix(multidb): allow associations across databases to work properly

- app/services/forest_liana/scope_manager.rb
> fix: dynamic scopes

- app/controllers/forest_liana/resources_controller.rb
- app/controllers/forest_liana/smart_actions_controller.rb
- app/controllers/forest_liana/stats_controller.rb
- app/services/forest_liana/permissions_checker.rb
- app/services/forest_liana/token.rb
- spec/requests/actions_controller_spec.rb
- spec/requests/count_spec.rb
- spec/requests/resources_spec.rb
- spec/requests/stats_spec.rb
- spec/services/forest_liana/permissions_checker_acl_disabled_spec.rb
- spec/services/forest_liana/permissions_checker_acl_enabled_spec.rb
- spec/services/forest_liana/permissions_checker_live_queries_spec.rb
> fix(charts): user with permissions level that allows charts creation or edition should always be allow to perform charts requests  released

- app/services/forest_liana/line_stat_getter.rb
- app/services/forest_liana/stat_getter.rb
- spec/dummy/app/models/owner.rb
- spec/services/forest_liana/line_stat_getter_spec.rb
> fix(charts): remove any sort on chart and remove default join behaviour on line chart

- lib/forest_liana/bootstrapper.rb
> fix(apimap): format apimap liana version

- app/services/forest_liana/ability/permission/smart_action_checker.rb
- spec/services/forest_liana/ability/permission/smart_action_checker_spec.rb
> fix(conditional-approval): update condition to check if user can trigger the action

- app/controllers/forest_liana/smart_actions_controller.rb
- app/services/forest_liana/ability.rb
- app/services/forest_liana/schema_utils.rb
- spec/services/forest_liana/ability/ability_spec.rb
> fix: raise error when an action is call on a smartcollection

- .releaserc.js
> chore: merge main into beta

- lib/forest_liana/engine.rb
> fix: developers can disable automatic schema send

- app/services/forest_liana/ability/permission.rb
> fix(permissions): use forest collection name for check the permission

- app/services/forest_liana/ability/permission.rb
- spec/requests/actions_controller_spec.rb
> fix(action): authorize all actions on development environment

- app/controllers/forest_liana/actions_controller.rb
Co-authored-by: Arun-V00222 <[arunshunmugam.j@vivriticapital.com](mailto:arunshunmugam.j@vivriticapital.com)>
> fix(hooks): use exact namespace to prevent controller conflict

- Gemfile
- Gemfile.lock
- app/services/forest_liana/operator_date_interval_parser.rb
- spec/services/forest_liana/filters_parser_spec.rb
> fix(operator): replace the hard-coded duration by the duration variable

- config/routes.rb
- config/routes/actions.rb
- spec/dummy/lib/forest_liana/collections/island.rb
- spec/requests/actions_controller_spec.rb
> fix(smartaction):  register custom endpoint for load/changes hooks

- app/controllers/forest_liana/associations_controller.rb
> fix: reporter error on dissociate action

- app/services/forest_liana/ability/permission.rb
> fix: allow charts with dynamic query using record id

- app/controllers/forest_liana/resources_controller.rb
> fix: destroy record with restriction on children

- app/controllers/forest_liana/authentication_controller.rb
- app/services/forest_liana/authentication.rb
- config/initializers/errors.rb
- spec/requests/authentications_spec.rb
> fix(authentication): return errors detail instead of generic error 500

- .github/workflows/build.yml
- .releaserc.js
- app/services/forest_liana/stat_getter.rb
- app/services/forest_liana/value_stat_getter.rb
- spec/services/forest_liana/line_stat_getter_spec.rb
- spec/services/forest_liana/pie_stat_getter_spec.rb
- spec/services/forest_liana/value_stat_getter_spec.rb
> fix: security vulnerabilities RCE

- .github/workflows/build.yml
> chore: update CI configuration [force release]

- .github/workflows/build.yml
- app/services/forest_liana/search_query_builder.rb
> feat: allow search on UUID v7 and v8 

- .github/workflows/build.yml
- package.json
- yarn.lock
> fix(security): patch commitlint dependency vulnerabilities

- yarn.lock
> fix(security): patch lodash dependency vulnerabilities

- yarn.lock
> fix(security): patch ansi-regex dependency vulnerabilities

- yarn.lock
> fix(security): patch http-cache-semantics dependency vulnerabilities

- yarn.lock
> fix(security): patch hosted-git-info dependency vulnerabilities

- yarn.lock
> fix(security): patch path-parse dependency vulnerabilities

- yarn.lock
> fix(security): patch npm dependency vulnerabilities

- app/services/forest_liana/search_query_builder.rb
> feat: add multiple sort support

- app/services/forest_liana/ability/permission.rb
- spec/requests/stats_spec.rb
>  fix(permission): fix chart permissions to work properly with multiple filter on 8.x.x

- lib/forest_liana/mixpanel_event.rb
> fix: require ostruct in lib/forest_liana/mixpanel_event.rb (fixes #672)

- app/services/forest_liana/belongs_to_updater.rb
> fix: remove downcase on model name when updated polymorphic association

- app/services/forest_liana/belongs_to_updater.rb
> fix: remove downcase on model name when updated polymorphic association on 8.x.x

- Gemfile.lock
> fix(security): patch nokogiri dependency vulnerabilities

- app/controllers/forest_liana/application_controller.rb
> fix(permission): send api response for 409 error

- app/services/forest_liana/ability/permission.rb
- spec/services/forest_liana/ability/permission_spec.rb
> fix(permission): refetch permission if collection name doesn't exist

- app/services/forest_liana/utils/context_variables.rb
- spec/services/forest_liana/utils/context_variables_injector_spec.rb
- spec/services/forest_liana/utils/context_variables_spec.rb
> fix: ensure correct values are returned for user tags in context variables

- app/services/forest_liana/resources_getter.rb
> fix(action): fix get_ids_from_request helper call on related data

- Gemfile
- Gemfile.lock
- config/initializers/arel-helpers.rb
- forest_liana.gemspec
> fix: remove arel-helpers to enable Rails 8 compatibility

- app/serializers/forest_liana/serializer_factory.rb
> fix(serializer): provide more information when association can't be loaded

- app/services/forest_liana/forest_api_requester.rb
- spec/services/forest_liana/forest_api_requester_spec.rb
> fix(forest-requester): don't swallow error anymore

- app/services/forest_liana/resources_getter.rb
- app/services/forest_liana/scope_manager.rb
- spec/services/forest_liana/scope_manager_spec.rb
> feat: enable context variable usage in segment queries

- config/routes.rb
> feat(inbox): add new route count post for inbox feature

- app/services/forest_liana/utils/context_variables_injector.rb
- spec/services/forest_liana/utils/context_variables_injector_spec.rb
> fix: prevent infinite loops in context variable injection

- config/routes.rb
> feat(inbox): rename route search to query

- app/controllers/forest_liana/application_controller.rb
> fix(export): format relation model name for matching collection

- lib/forest_liana/bootstrapper.rb
> fix(api_map): display more information when we don't understand why schema could not be sent

- lib/forest_liana/schema_file_updater.rb
> fix(schema-updater): properly write validation regex when writing schema on disk

- lib/forest_liana/engine.rb
> fix(schema-bypass): properly bypass schema update using forest_disable_auto_schema_apply

- app/services/forest_liana/ip_whitelist.rb
> fix(startup): display current env secret when ip whitelist fails to ease debugging

- app/services/forest_liana/filters_parser.rb
- spec/services/forest_liana/filters_parser_spec.rb
> feat(operators): add i_contains operator support

- app/services/forest_liana/line_stat_getter.rb
- spec/services/forest_liana/line_stat_getter_spec.rb
> fix(charts): properly format week of year

- app/serializers/forest_liana/serializer_factory.rb
> fix(serializer): do not execute smart feature on object like a native attribute

- app/serializers/forest_liana/serializer_factory.rb
- app/services/forest_liana/resources_getter.rb
> fix: preload polymorphic associations to improve performance

- app/services/forest_liana/resources_getter.rb
- spec/services/forest_liana/resources_getter_spec.rb
Reverts ForestAdmin/forest-rails#743
issue on coverage
> Revert "fix(filters): properly parse filters from request params"

- .github/workflows/build.yml
- app/services/forest_liana/resources_getter.rb
- spec/services/forest_liana/resources_getter_spec.rb
> fix(filters): properly parse filters from request params

- app/serializers/forest_liana/serializer_factory.rb
- spec/services/forest_liana/serializer_factory_spec.rb
> fix: serializer on relationships

- app/services/forest_liana/has_many_getter.rb
- spec/services/forest_liana/has_many_getter_spec.rb
> fix(has_many_getter): add has_one support

- app/controllers/forest_liana/application_controller.rb
- app/helpers/forest_liana/decoration_helper.rb
- spec/helpers/forest_liana/decoration_helper_spec.rb
- spec/requests/actions_controller_spec.rb
> fix: enable unoptimized mode in serializer when searchToEdit flag is set

- app/controllers/forest_liana/application_controller.rb
- spec/requests/actions_controller_spec.rb
> fix: key conflicts in fields for same-collection smart relations
