ForestAdmin/forest-rails

- app/controllers/forest_liana/sessions_controller.rb
Here a quick fix that prevent this:
```
….1/app/controllers/forest_liana/sessions_controller.rb:  32:in `check_user'
….1/app/controllers/forest_liana/sessions_controller.rb:   8:in `create'
…e/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:  30:in `process'
/usr/local/bundle/gems/rack-cors-0.4.0/lib/rack/cors.rb:  80:in `call'
```
> Fixed type instance variable

- app/deserializers/forest_liana/resource_deserializer.rb
When I update a model via Forest Admin, browser submits image attribute even if it's marked readonly and if it hasn't changed. In this case browser passes a URL for the existing image, which caused `ForestLiana::Base64StringIO.initialize` to throw an `ArgumentError`.
This PR is to ignore carrierwave fields (by removing related key from attributes hash) which contain incorrect (non-base64 data) strings.
> Test uploaded file against Base64 regexp for Carrierwave

- CHANGELOG.md
- lib/forest_liana/collection.rb
Example:
```ruby
class Forest::Customer
include ForestLiana::Collection
collection :customers
belongs_to :delivery, reference: 'delivery_men.id' do
DeliveryMan.first
end
end
```
> [+] Smart Fields - Support belongs_to smart fields

- CHANGELOG.md
- app/services/forest_liana/controller_factory.rb
Hi,
I couldn't launch my server with forest-rails gem because the class `ControllerFactory` was using `ResourcesController` which is a common name, used in my case in another gem.
So I just add the namespace in your code and everything is working fine.
> [*] Server Start - Use namespace for ResourcesController to prevent conflicts

- CHANGELOG.md
- app/controllers/forest_liana/application_controller.rb
Remove unnecessary leeway of 30s on JWTs
https://trello.com/c/6P4KWrmE/3477-autentication-add-expiration-to-the-jwt-tokens
> Autentication - Add expiration to the JWT tokens

- CHANGELOG.md
- app/services/forest_liana/search_query_builder.rb
Add little code to handle 'or' filter type when performing the search.
https://trello.com/c/Yv2J5C8k/3478-filters-support-or-filter-type-with-conditions-on-belongsto-hasone-fields
> Filters - Support OR filter type with conditions on belongsTo/hasOne fields

- CHANGELOG.md
- lib/forest_liana.rb
- lib/forest_liana/bootstraper.rb
- test/forest_liana_test.rb
We had hardcoded the directory used for configuring more data models. Hardcoding this value made it difficult to set a custom directory to define these files. It also caused `zeitwerk` to throw a warning when trying to autoload the extra classes. We added a `config_dirs` accessor to the configuration module. Adding this attribute allows us to set this directory ourselves.
> Add initialisation of configuration directories

- CHANGELOG.md
- app/services/forest_liana/stripe_invoices_getter.rb
- app/services/forest_liana/stripe_payments_getter.rb
- app/services/forest_liana/stripe_sources_getter.rb
- app/services/forest_liana/stripe_subscriptions_getter.rb
Fixes deprecated usage of the `all` function. 
Support stopped following this PR: https://github.com/stripe/stripe-ruby/pull/823/files
> [*] Stripe Integration - Replace usage of the deprecated `all` function by the `list` one from stripe gem

- .travis.yml
- CHANGELOG.md
Currently, Travis pulls the latest version of the bundler, whereas in our gemfile.lock, it is specified that the `1.17.3` is required.
> [*] Technical - Fix CI build

- CHANGELOG.md
- app/services/forest_liana/has_many_getter.rb
See @SteveBunlon's comment: https://github.com/ForestAdmin/forest-rails/pull/345#issuecomment-592613766
> When I filter the related data, the count is not correct (see at the bottom right of the screen)
This PR consider filters before counting related data.
> [*] Has Many Relationships - Fix records count, i.e consider filters when counting

- CHANGELOG.md
- app/controllers/forest_liana/resources_controller.rb
- app/controllers/forest_liana/router.rb
- app/services/forest_liana/has_many_dissociator.rb
- app/services/forest_liana/resources_getter.rb
- config/routes.rb
Add "select all records" mode for rails liana. See: https://app.clickup.com/t/3rhj80
```ruby
class Forest::ActorsController < ForestLiana::ApplicationController
def mark_as_live
actor_ids = ForestLiana::ResourcesGetter.get_ids_from_request(params)
render json: { success: 'Data successfuly imported!' }
end
end
```
You have ton use this branch as a dependency in `Gemfile`
```
gem 'forest_liana', path: '../forest-rails'
```
Then you have to update `forestadmin` [liana feature file](https://github.com/ForestAdmin/forestadmin/blob/5c97aa9392c278b9aed616f1ea60086c7e11f4bf/app/services/liana-features.js) to enable "select all" feature:
```javascript
{
name: 'tableViewSelectAllRecords',
minimalVersion: {
'forest-express-sequelize': '6.0.0',
'forest-express-mongoose': '6.0.0',
'forest-rails': …
```
> [+] Resources getter - Add a get_ids_from_request method to get all models IDs given a query or an ID list

- app/controllers/forest_liana/actions_controller.rb
- app/controllers/forest_liana/application_controller.rb
- app/helpers/forest_liana/widgets_helper.rb
- spec/requests/actions_controller_spec.rb
> fix(smart-actions): transform legacy widgets in hooks

- app/services/forest_liana/resource_creator.rb
- app/services/forest_liana/resource_updater.rb
(See also: https://github.com/ForestAdmin/forest-rails/pull/411 & https://github.com/ForestAdmin/forest-rails/pull/408)
https://blog.saeloun.com/2019/04/15/rails-6-deprecates-update-attributes.html
> fix: use update instead of update_attributes to ensure rails 6.1 compatibility

- app/controllers/forest_liana/authentication_controller.rb
- app/services/forest_liana/authorization_getter.rb
- config/initializers/error-messages.rb
- config/initializers/errors.rb
This modification is needed to identify why the authorization failed, and display the correct error message in the frontend.
In this case, instead of a 500 with an error message, we get a 403 and the error's name correctly encoded in the response, just as the server sends errors.
> feat(auth): return a specific error during authorization if received  an error about 2FA (#d513um)

- app/controllers/forest_liana/authentication_controller.rb
See [this blog post](https://www.honeybadger.io/blog/why-is-uri-join-so-counterintuitive/) for the why.
> fix(authentication): authentication error when the agent uses a prefix path in its url (#fb79c7)

- lib/forest_liana/engine.rb
Fixes issues in generating `.forestadmin-schema.json` ending up in an empty set of collections for Rails 6 projects using the Classic Autoloader.
The issue has been raised [here](https://community.forestadmin.com/t/forest-liana-upgrade-empty-collections/2502?u=alexis_philippart_de)
> fix(schema): generate the schema properly on server start while using the classic Autoloader using Rails 5

- Gemfile
- Gemfile.lock
- app/controllers/forest_liana/application_controller.rb
- app/controllers/forest_liana/associations_controller.rb
- app/controllers/forest_liana/base_controller.rb
- app/controllers/forest_liana/resources_controller.rb
- app/serializers/forest_liana/intercom_attribute_serializer.rb
- app/serializers/forest_liana/intercom_conversation_serializer.rb
- app/serializers/forest_liana/mixpanel_event_serializer.rb
- app/serializers/forest_liana/serializer_factory.rb
- app/serializers/forest_liana/stat_serializer.rb
- app/serializers/forest_liana/stripe_bank_account_serializer.rb
- app/serializers/forest_liana/stripe_card_serializer.rb
- app/serializers/forest_liana/stripe_invoice_serializer.rb
- app/serializers/forest_liana/stripe_payment_serializer.rb
- app/serializers/forest_liana/stripe_subscription_serializer.rb
- forest_liana.gemspec
- lib/forest_liana/bootstrapper.rb
BREAKING CHANGE: Switch from jsonapi-serializers to forestadmin-jsonapi-serializers to serialize data to the JSONAPI format, mainly to avoid conflict with the jsonapi-serializer library
> chore(force-release): now using forestadmin-jsonapi-serializers instead of the jsonapi-serializers gem

- Gemfile
- Gemfile.lock
- app/controllers/forest_liana/application_controller.rb
- app/controllers/forest_liana/associations_controller.rb
- app/controllers/forest_liana/base_controller.rb
- app/controllers/forest_liana/resources_controller.rb
- app/serializers/forest_liana/intercom_attribute_serializer.rb
- app/serializers/forest_liana/intercom_conversation_serializer.rb
- app/serializers/forest_liana/mixpanel_event_serializer.rb
- app/serializers/forest_liana/serializer_factory.rb
- app/serializers/forest_liana/stat_serializer.rb
- app/serializers/forest_liana/stripe_bank_account_serializer.rb
- app/serializers/forest_liana/stripe_card_serializer.rb
- app/serializers/forest_liana/stripe_invoice_serializer.rb
- app/serializers/forest_liana/stripe_payment_serializer.rb
- app/serializers/forest_liana/stripe_subscription_serializer.rb
- forest_liana.gemspec
- lib/forest_liana/bootstrapper.rb
BREAKING CHANGE: Switch from jsonapi-serializers to forestadmin-jsonapi-serializers to serialize data to the JSONAPI format, mainly to avoid conflict with the jsonapi-serializer library
> fix(dependency): now using forestadmin-jsonapi-serializers instead of the jsonapi-serializers gem

- app/controllers/forest_liana/smart_actions_controller.rb
- app/services/forest_liana/utils/beta_schema_utils.rb
Be more flexible about endpoint beginning with slash.
The documentation provides default endpoint starting with slash
/ https://docs.forestadmin.com/documentation/v/v6/reference-guide/actions/create-and-manage-smart-actions#available-smart-action-options
But is was not working when endpoint starts with slash.
> fix: allow smart action endpoints to start with slashes

- app/services/forest_liana/filters_parser.rb
- spec/services/forest_liana/filters_parser_spec.rb
- spec/services/forest_liana/resource_updater_spec.rb
Although SQLite supports the surrounding parentheses for all operators, Postgresql does not.
> fix: restrict the use of surrounding parentheses only to IN operator

- Gemfile
- Gemfile.lock
> fix: update arel-helpers dependency

- app/services/forest_liana/base_getter.rb
- app/services/forest_liana/has_many_getter.rb
- app/services/forest_liana/pie_stat_getter.rb
- app/services/forest_liana/resource_getter.rb
- app/services/forest_liana/resources_getter.rb
- app/services/forest_liana/value_stat_getter.rb
- spec/dummy/app/models/island.rb
- spec/dummy/app/models/tree.rb
- spec/helpers/forest_liana/query_helper_spec.rb
- spec/services/forest_liana/resources_getter_spec.rb
- spec/services/forest_liana/schema_adapter_spec.rb
In Rails, when attempting to `eager_load` an association that depends on the instance, I get the following error:
```
/activerecord-7.0.3/lib/active_record/reflection.rb:500:
in `check_eager_loadable!':
The association scope 'eponymous_tree' is instance dependent (the scope block takes an argument).
Eager loading instance dependent scopes is not supported.
(ArgumentError)
```
Since Forest employs `eager_load` to reduce load to the database, an instance dependent association causes errors in table and details views and prevents their use.
The suggested fix allows all Rails version to work. It also contains an optimization of those associations for Rails v7 (the only version that supports this optimization). Older versions of Rails, instead of an error they will work, but will use an …
> fix: handle instance dependent associations

- lib/forest_liana/bootstrapper.rb
- spec/dummy/app/models/application_record.rb
- spec/dummy/app/models/product.rb
- spec/dummy/app/models/reference.rb
- spec/dummy/app/models/sub_application_record.rb
- spec/lib/forest_liana/bootstrapper_spec.rb
When the application defines multiple ActiveRecord application classes (for example [`ApplicationRecord`, as Rails documentation currently suggests](https://guides.rubyonrails.org/active_record_basics.html#creating-active-record-models)), the Forest schema contains duplicates of their subclass fields. It seems that the problem stems from a couple of innocent looking code lines:
- The use of `subclasses` (which only gets direct children) in for the starting point:
https://github.com/ForestAdmin/forest-rails/blob/d6d381d208335c54056a5dfea0db2281758041cb/lib/forest_liana/bootstrapper.rb#L111 and `descendants` (which gets direct and indirect children) in others:
https://github.com/ForestAdmin/forest-rails/blob/d6d381d208335c54056a5dfea0db2281758041cb/lib/forest_liana/bootstrapper.rb#L117 and …
> fix: prevent duplication of models from multiple ActiveRecord application classes

- app/services/forest_liana/base_getter.rb
- spec/dummy/app/models/manufacturer.rb
- spec/dummy/app/models/product.rb
- spec/dummy/db/migrate/20220727114450_create_manufacturers.rb
- spec/dummy/db/migrate/20220727114930_add_columns_to_products.rb
- spec/dummy/db/schema.rb
- spec/lib/forest_liana/bootstrapper_spec.rb
- spec/services/forest_liana/resources_getter_spec.rb
The previous code in https://github.com/ForestAdmin/forest-rails/pull/572 introduced a couple of issues:
- Some association definitions do not have an `inverse_of` declaration. For those associations the logic was detecting the associations to be running on a different database (which might not be necessarily true). Instead, I used the `klass` method, which Rails always calculates, even for very old versions of Rails. 
- The `resourceDatabase` and `targetModelDatabase` were using different types and therefore all the given `@includes` associations were considered to be running on a different database. I have now used the same method on both, which will correctly detect if they are using the same database.
These were preventing some associations from being eager load correctly and …
> fix(multidb): fix issue with multiple connection detection

- app/services/forest_liana/schema_adapter.rb
We get different results from the schema generation between
Linux and MacOS, the problem is that sort_by isn't stable:
https://stackoverflow.com/a/15442966
https://bugs.ruby-lang.org/issues/1089
The change was introduced recently [here](https://github.com/ForestAdmin/forest-rails/pull/561) and it already has tests (probably hard to test across OS)
> Use stable sort for schema fields so we get same results across OS

- lib/forest_liana/bootstrapper.rb
The schema version generation resulted in a `null` value:
```ruby
ForestLiana::VERSION
ForestLiana::VERSION.sub!('.beta', '-beta')
```
```ruby
ForestLiana::VERSION.sub('.beta', '-beta')
```
> fix: schema version generation for all versions

- .github/workflows/build.yml
- .releaserc.js
- app/services/forest_liana/stat_getter.rb
- app/services/forest_liana/value_stat_getter.rb
- spec/services/forest_liana/line_stat_getter_spec.rb
- spec/services/forest_liana/pie_stat_getter_spec.rb
- spec/services/forest_liana/value_stat_getter_spec.rb
> fix: security vulnerabilities RCE on 8.x.x

- app/deserializers/forest_liana/resource_deserializer.rb
- app/helpers/forest_liana/query_helper.rb
- app/serializers/forest_liana/serializer_factory.rb
- app/services/forest_liana/apimap_sorter.rb
- app/services/forest_liana/base_getter.rb
- app/services/forest_liana/belongs_to_updater.rb
- app/services/forest_liana/has_many_getter.rb
- app/services/forest_liana/schema_adapter.rb
- app/services/forest_liana/schema_utils.rb
- lib/forest_liana/bootstrapper.rb
- lib/forest_liana/schema_file_updater.rb
- lib/tasks/send_apimap.rake
- spec/dummy/app/models/address.rb
- spec/dummy/app/models/user.rb
- spec/dummy/db/migrate/20231117084236_create_addresses.rb
- spec/dummy/db/schema.rb
- spec/helpers/forest_liana/query_helper_spec.rb
- spec/lib/forest_liana/bootstrapper_spec.rb
- spec/lib/forest_liana/schema_file_updater_spec.rb
- spec/requests/resources_spec.rb
- spec/services/forest_liana/schema_adapter_spec.rb
- spec/spec_helper.rb
> feat: add polymorphic associations support

- CHANGELOG.md
- Gemfile.lock
- app/services/forest_liana/schema_adapter.rb
- app/services/forest_liana/schema_utils.rb
- lib/forest_liana/version.rb
- package.json
- spec/services/forest_liana/schema_adapter_spec.rb
- spec/spec_helper.rb
> chore: release 9.0.0-beta into main

- yarn.lock
> fix(security): patch semver-regex dependency vulnerabilities

- app/services/forest_liana/ability/permission.rb
- app/services/forest_liana/ability/permission/smart_action_checker.rb
- app/services/forest_liana/filters_parser.rb
- app/services/forest_liana/leaderboard_stat_getter.rb
- app/services/forest_liana/line_stat_getter.rb
- app/services/forest_liana/pie_stat_getter.rb
- app/services/forest_liana/scope_manager.rb
- app/services/forest_liana/utils/context_variables.rb
- app/services/forest_liana/utils/context_variables_injector.rb
- app/services/forest_liana/value_stat_getter.rb
- spec/requests/actions_controller_spec.rb
- spec/requests/count_spec.rb
- spec/requests/resources_spec.rb
- spec/requests/stats_spec.rb
- spec/services/forest_liana/filters_parser_spec.rb
- spec/services/forest_liana/has_many_getter_spec.rb
- spec/services/forest_liana/line_stat_getter_spec.rb
- spec/services/forest_liana/pie_stat_getter_spec.rb
- spec/services/forest_liana/resource_updater_spec.rb
- spec/services/forest_liana/resources_getter_spec.rb
- spec/services/forest_liana/scope_manager_spec.rb
- spec/services/forest_liana/utils/context_variables_injector_spec.rb
- spec/services/forest_liana/utils/context_variables_spec.rb
- spec/services/forest_liana/value_stat_getter_spec.rb
> feat: add support for workspace context in charts

- app/services/forest_liana/query_stat_getter.rb
> fix(query): allow user using context variables into query

- lib/forest_liana/bootstrapper.rb
This PR removes an old warning concerning the use of the parameter : "forest_application_url" and avoids the use of "Rails.application.secrets" now deprecated on Rails >= 7.1
> fix: remove warning  forest_application_url

- app/services/forest_liana/search_query_builder.rb
> fix(search): does not apply the extended search for polymorphic relationships

- app/controllers/forest_liana/application_controller.rb
- app/services/forest_liana/ability/exceptions/unknown_collection.rb
- app/services/forest_liana/ability/permission.rb
- spec/dummy/app/controllers/forest/islands_controller.rb
- spec/dummy/config/routes.rb
- spec/dummy/lib/forest_liana/collections/island.rb
- spec/requests/actions_controller_spec.rb
- spec/services/forest_liana/ability/permission_spec.rb
> fix(permission): forward action approval exception for return expected response

- app/services/forest_liana/base_getter.rb
- app/services/forest_liana/filters_parser.rb
- app/services/forest_liana/resources_getter.rb
- spec/services/forest_liana/filters_parser_spec.rb
- spec/services/forest_liana/resources_getter_spec.rb
> fix: improve quey with duplicate alias

- app/controllers/forest_liana/associations_controller.rb
- app/services/forest_liana/has_many_dissociator.rb
> fix(association): return bad request when associated record is not destroy

- app/controllers/forest_liana/associations_controller.rb
- app/services/forest_liana/has_many_dissociator.rb
> fix(association): return bad request if associated record is not destroy on 8.x.x

- app/controllers/forest_liana/actions_controller.rb
- app/models/forest_liana/model/action.rb
- app/services/forest_liana/apimap_sorter.rb
- app/services/forest_liana/smart_action_form_parser.rb
- lib/forest_liana/schema_file_updater.rb
- spec/dummy/lib/forest_liana/collections/island.rb
- spec/requests/actions_controller_spec.rb
- spec/services/forest_liana/smart_action_form_parser_spec.rb
> feat(form): support layout elements in smart action form hooks 

- lib/forest_liana/collection.rb
```
field :addressable_type, type: 'String', polymorphic_key: true, is_filterable: true do
object.addressable_type
end
field :addressable_id, type: 'String', polymorphic_key: true do
object.addressable_type
end
```
> feat(smart-field): add new options to support native polymorphic fields

- app/services/forest_liana/scope_manager.rb
- spec/services/forest_liana/scope_manager_spec.rb
> fix(scopes): prevent unnecessary HTTP call despite caching

- lib/forest_liana/collection.rb
> fix: avoid smart feature to be load more one time

- app/services/forest_liana/schema_adapter.rb
> fix(validations): ignore default before validations

- app/services/forest_liana/forest_api_requester.rb
> fix(forest-requester): forest reporter now gets actual error instead of message

- Gemfile
- config/routes.rb
> feat(inbox): add new route post for inbox feature

- app/services/forest_liana/filters_parser.rb
- app/services/forest_liana/operator_date_interval_parser.rb
- app/services/forest_liana/schema_utils.rb
- test/services/forest_liana/operator_date_interval_parser_test.rb
> fix(filters): filtering on date only fields now format value properly

- app/services/forest_liana/filters_parser.rb
- app/services/forest_liana/operator_date_interval_parser.rb
> fix(filters): get collection name with the right format

- app/services/forest_liana/base_getter.rb
- app/services/forest_liana/resources_getter.rb
> feat: reduce redundant queries on cross-db belongs_to

- app/serializers/forest_liana/serializer_factory.rb
- app/services/forest_liana/base_getter.rb
- app/services/forest_liana/has_many_getter.rb
- app/services/forest_liana/resources_getter.rb
> feat: improve performance by avoiding unnecessary jointure on belongsTo relations

- app/services/forest_liana/aggregation_helper.rb
- app/services/forest_liana/leaderboard_stat_getter.rb
- app/services/forest_liana/pie_stat_getter.rb
- spec/services/forest_liana/pie_stat_getter_spec.rb
> fix: rails 8 compatibility for stat aggregators

- lib/forest_liana/schema_file_updater.rb
The line in the SchemaFileUpdater that was supposed to sort the fields of a collection in a schema was not doing anything. This fixes this, making the schema more reliable and easier to read.
No impact
> Fix field sorting

- app/services/forest_liana/search_query_builder.rb
Given an Active Record model with PK of type UUID:
```
+class CreateCardTransactions < ActiveRecord::Migration[6.0]
+  def change
+    create_table :card_transactions, id: :uuid do |t|
+      t.timestamps
+    end
+  end
+end
```
And with a Forest collection with `search_fields` configured only for `id`
field:
```
module Forest
class CardTransaction
include ForestLiana::Collection
collection :Card__Transaction
search_fields %w[id]
end
end
```
`SearchQueryBuilder` will generate an invalid SQL query with an empty
`WHERE` statement if search term doesn't meet `REGEX_UUID` format:
```sql
SELECT
"transactions"."id" AS t0_r0,
"transactions"."processed_at" AS
FROM "transactions"
WHERE  ORDER BY "transactions"."created_at"
DESC LIMIT $1 OFFSET $2  [["LIMIT", 10], ["OFFSET", 0]]
```
> fix: Skip WHERE when computed search conditions are empty
